from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    MARKET_NOT_FOUND = "MARKET_NOT_FOUND"
    MARKET_SELECTION_AMBIGUOUS = "MARKET_SELECTION_AMBIGUOUS"
    MARKET_CLOSED = "MARKET_CLOSED"
    MARKET_NOT_ACCEPTING_ORDERS = "MARKET_NOT_ACCEPTING_ORDERS"
    MARKET_TOKEN_MAPPING_INVALID = "MARKET_TOKEN_MAPPING_INVALID"
    MARKET_ORDER_BOOK_MISSING = "MARKET_ORDER_BOOK_MISSING"
    MARKET_ORDER_BOOK_CROSSED = "MARKET_ORDER_BOOK_CROSSED"
    MARKET_QUOTE_UNAVAILABLE = "MARKET_QUOTE_UNAVAILABLE"

    RULE_STATION_AMBIGUOUS = "RULE_STATION_AMBIGUOUS"
    RULE_DATE_AMBIGUOUS = "RULE_DATE_AMBIGUOUS"
    RULE_TIMEZONE_AMBIGUOUS = "RULE_TIMEZONE_AMBIGUOUS"
    RULE_UNIT_AMBIGUOUS = "RULE_UNIT_AMBIGUOUS"
    RULE_BIN_AMBIGUOUS = "RULE_BIN_AMBIGUOUS"
    RULE_ROUNDING_AMBIGUOUS = "RULE_ROUNDING_AMBIGUOUS"
    RULE_WINDOW_AMBIGUOUS = "RULE_WINDOW_AMBIGUOUS"
    RULE_OBSERVATION_WINDOW_AMBIGUOUS = "RULE_OBSERVATION_WINDOW_AMBIGUOUS"
    RULE_SETTLEMENT_SOURCE_AMBIGUOUS = "RULE_SETTLEMENT_SOURCE_AMBIGUOUS"

    DATA_MARKET_METADATA_MISSING = "DATA_MARKET_METADATA_MISSING"
    DATA_MARKET_METADATA_STALE = "DATA_MARKET_METADATA_STALE"
    DATA_ORDER_BOOK_MISSING = "DATA_ORDER_BOOK_MISSING"
    DATA_ORDER_BOOK_STALE = "DATA_ORDER_BOOK_STALE"
    DATA_ORDER_BOOK_EMPTY = "DATA_ORDER_BOOK_EMPTY"
    DATA_ORDER_BOOK_INVALID = "DATA_ORDER_BOOK_INVALID"
    DATA_OBSERVATION_MISSING = "DATA_OBSERVATION_MISSING"
    DATA_OBSERVATION_STALE = "DATA_OBSERVATION_STALE"
    DATA_FORECAST_MISSING = "DATA_FORECAST_MISSING"
    DATA_FORECAST_STALE = "DATA_FORECAST_STALE"
    DATA_FORECAST_COVERAGE_GAP = "DATA_FORECAST_COVERAGE_GAP"
    DATA_AS_OF_VIOLATION = "DATA_AS_OF_VIOLATION"
    DATA_OUT_OF_ORDER = "DATA_OUT_OF_ORDER"
    DATA_STALE = "DATA_STALE"

    PROBABILITY_PARTITION_INVALID = "PROBABILITY_PARTITION_INVALID"
    PROBABILITY_VALUE_INVALID = "PROBABILITY_VALUE_INVALID"
    PROBABILITY_SUM_INVALID = "PROBABILITY_SUM_INVALID"

    EDGE_BELOW_THRESHOLD = "EDGE_BELOW_THRESHOLD"
    DEPTH_INSUFFICIENT = "DEPTH_INSUFFICIENT"
    RISK_LIMIT_REACHED = "RISK_LIMIT_REACHED"
    RISK_CASH_INSUFFICIENT = "RISK_CASH_INSUFFICIENT"
    RISK_CITY_DAY_LIMIT = "RISK_CITY_DAY_LIMIT"

    PAPER_DISABLED_IN_SHADOW = "PAPER_DISABLED_IN_SHADOW"
    PAPER_STATE_INVALID = "PAPER_STATE_INVALID"
    PAPER_ORDER_REJECTED = "PAPER_ORDER_REJECTED"

    SYSTEM_RUNNER_STALE = "SYSTEM_RUNNER_STALE"
    SYSTEM_RUNNER_LOCKED = "SYSTEM_RUNNER_LOCKED"
    SYSTEM_SOURCE_ERROR = "SYSTEM_SOURCE_ERROR"
    SYSTEM_DATABASE_ERROR = "SYSTEM_DATABASE_ERROR"
